name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Release Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.version.outputs.tag }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}
        run: .github/workflows/release.sh
