name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Release Script
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          RELEASE_VERSION: ${{ steps.version.outputs.tag }}
        run: .github/workflows/release.sh
