name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: run script
        run: .github/workflows/test.sh
