name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Script
        run: .github/workflows/test.sh
      - name: Show Kordamp Groovy Test Project
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: kordamp-groovy
          path: /tmp/kordamp-groovy-test
